apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tkc-deploy
  namespace: demo1
spec:
  project: default
  destination:
    namespace: demo1
    server: https://kubernetes.default.svc
  source:
    path: tkc
    repoURL: https://github.com/papivot/vks-argocd-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
  - group: cluster.x-k8s.io
    kind: Cluster
    jqPathExpressions:
    - .spec.topology.variables[] | select((.name == "user") or (.name == "TKR_DATA") or (.name == "clusterEncryptionConfigYaml") or (.name == "extensionCert"))