apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-app-cm.yaml
- argocd-job.yaml
- workload-cluster.yaml

namespace: demo2

images:
- name: whoami6443/argocd-hook
  newName: us-central1-docker.pkg.dev/navneet-410819/whoami6443-hub/whoami6443/argocd-hook

patches:
  - patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: app-tkc-creation
      spec:
        template:
          spec:
            serviceAccountName: argocd-application-controller # {NAME-OF-ARGOCD-INSTANCE}-argocd-application-controller
    target:
      kind: Job
      name: app-tkc-creation
