apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-app-cm.yaml
- argocd-job.yaml
- workload-cluster.yaml

namespace: demo1

images:
- name: whoami6443/argocd-hook
  newName: us-central1-docker.pkg.dev/navneet-410819/whoami6443-hub/whoami6443/argocd-hook