apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:  
  name: tanzu-standard  
  namespace: tkg-system
spec:  
  fetch:    
    imgpkgBundle:      
      image: projects.packages.broadcom.com/vsphere/iaas/packages/2024.9.18/tanzu-standard-packages:v2024.9.18